"""hopeful

Revision ID: e1e64cdebae6
Revises: 
Create Date: 2025-03-07 11:17:43.193460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1e64cdebae6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('artist_spotify_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('image', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('artist_spotify_id', name=op.f('pk_artist'))
    )
    op.create_table('shows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('show_date', sa.String(length=15), nullable=False),
    sa.Column('venue', sa.String(length=64), nullable=False),
    sa.Column('venue_same_as', sa.String(length=256), nullable=False),
    sa.Column('concert_id', sa.String(length=64), nullable=False),
    sa.Column('artist_name', sa.String(length=64), nullable=False),
    sa.Column('artist_id', sa.String(length=64), nullable=False),
    sa.Column('artist_spotify_id', sa.String(), nullable=True),
    sa.Column('image', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['artist_spotify_id'], ['artist.artist_spotify_id'], name=op.f('fk_shows_artist_spotify_id_artist')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shows')),
    sa.UniqueConstraint('city', 'show_date', 'artist_name', name='unique_shows')
    )
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shows_artist_spotify_id'), ['artist_spotify_id'], unique=False)

    op.create_table('user_shows',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['shows.concert_id'], name=op.f('fk_user_shows_show_id_shows')),
    sa.ForeignKeyConstraint(['user_id'], ['user.spotify_id'], name=op.f('fk_user_shows_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', 'show_id', name=op.f('pk_user_shows'))
    )
    with op.batch_alter_table('user_shows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_shows_show_id'), ['show_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_shows_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_shows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_shows_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_shows_show_id'))

    op.drop_table('user_shows')
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shows_artist_spotify_id'))

    op.drop_table('shows')
    op.drop_table('artist')
    # ### end Alembic commands ###
